version: '3.8'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: ${INFLUXDB_DB}        
      INFLUXDB_HTTP_AUTH_ENABLED: 'true'       
      INFLUXDB_USER: ${INFLUXDB_USER}           
      INFLUXDB_USER_PASSWORD: ${INFLUXDB_USER_PASSWORD} 
      INFLUXDB_ADMIN_USER: ${INFLUXDB_ADMIN_USER}       
      INFLUXDB_ADMIN_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD} 
    volumes:
      - influxdb_data:/var/lib/influxdb
volumes:
  influxdb_data:
